name: "Trigger Another Repository Workflow"
description: "Triggers a workflow in another repository and waits for its completion."
inputs:
  token:
    description: "GitHub Personal Access Token"
    required: true
  repo:
    description: "Target repository (owner/repo)"
    required: true
  event_type:
    description: "The event type for repository_dispatch"
    required: true
  payload:
    description: "JSON payload to pass to the triggered workflow"
    required: false
    default: "{}"

runs:

  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      shell: bash

    - name: Trigger the workflow
      run: |
        python trigger_workflow.py \
          --token "${{ inputs.token }}" \
          --repo "${{ inputs.repo }}" \
          --event_type "${{ inputs.event_type }}" \
          --payload '${{ inputs.payload }}'
      shell: bash
