name: 'Trigger and Wait for this repository workflow'
description: 'Triggers a workflow in this repository and waits for its status (completed, failed, or canceled).'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT).'
    default: ${{ github.token }}
  repository:
    description: 'The full name of the repository to send the dispatch.'
    default: ${{ github.repository }}
  event_type:
    description: 'A custom webhook event name.'
    required: true
  timeout_minutes:
    description: 'Maximum time to wait for the workflow status (in minutes).'
    required: false
    default: '30'
  poll_interval_seconds:
    description: 'Interval (in seconds) between status checks.'
    required: false
    default: '30'
runs:
  using: "composite"

  steps:
    - name: Install Python Dependencies
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_EVENT_TYPE: ${{inputs.event_type}}  
      run: pip install -r "$GITHUB_ACTION_PATH/requirements.txt"

    - name: Run Notification Script
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_EVENT_TYPE: ${{inputs.event_type}}    
      run: python "$GITHUB_ACTION_PATH/trigger_and_wait.py"
      continue-on-error: false


