name: Trigger External Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger External Workflow
        uses: yourusername/trigger-workflow@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: "target-owner/target-repo"
          event_type: "custom_event"
          payload: '{ "key": "value" }'
